package com.spring.boot.springbootdemo.model;

public class UserRoleFunction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.LoginID
     *
     * @mbg.generated
     */
    private String loginID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.LastName
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.roleName
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.funname
     *
     * @mbg.generated
     */
    private String funname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.functionID
     *
     * @mbg.generated
     */
    private Integer functionID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.funcode
     *
     * @mbg.generated
     */
    private String funcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_role_function.funType
     *
     * @mbg.generated
     */
    private Integer funType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.id
     *
     * @return the value of v_user_role_function.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.id
     *
     * @param id the value for v_user_role_function.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.LoginID
     *
     * @return the value of v_user_role_function.LoginID
     *
     * @mbg.generated
     */
    public String getLoginID() {
        return loginID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.LoginID
     *
     * @param loginID the value for v_user_role_function.LoginID
     *
     * @mbg.generated
     */
    public void setLoginID(String loginID) {
        this.loginID = loginID == null ? null : loginID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.LastName
     *
     * @return the value of v_user_role_function.LastName
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.LastName
     *
     * @param lastName the value for v_user_role_function.LastName
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.roleName
     *
     * @return the value of v_user_role_function.roleName
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.roleName
     *
     * @param roleName the value for v_user_role_function.roleName
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.funname
     *
     * @return the value of v_user_role_function.funname
     *
     * @mbg.generated
     */
    public String getFunname() {
        return funname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.funname
     *
     * @param funname the value for v_user_role_function.funname
     *
     * @mbg.generated
     */
    public void setFunname(String funname) {
        this.funname = funname == null ? null : funname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.pid
     *
     * @return the value of v_user_role_function.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.pid
     *
     * @param pid the value for v_user_role_function.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.functionID
     *
     * @return the value of v_user_role_function.functionID
     *
     * @mbg.generated
     */
    public Integer getFunctionID() {
        return functionID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.functionID
     *
     * @param functionID the value for v_user_role_function.functionID
     *
     * @mbg.generated
     */
    public void setFunctionID(Integer functionID) {
        this.functionID = functionID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.url
     *
     * @return the value of v_user_role_function.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.url
     *
     * @param url the value for v_user_role_function.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.funcode
     *
     * @return the value of v_user_role_function.funcode
     *
     * @mbg.generated
     */
    public String getFuncode() {
        return funcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.funcode
     *
     * @param funcode the value for v_user_role_function.funcode
     *
     * @mbg.generated
     */
    public void setFuncode(String funcode) {
        this.funcode = funcode == null ? null : funcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_role_function.funType
     *
     * @return the value of v_user_role_function.funType
     *
     * @mbg.generated
     */
    public Integer getFunType() {
        return funType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_role_function.funType
     *
     * @param funType the value for v_user_role_function.funType
     *
     * @mbg.generated
     */
    public void setFunType(Integer funType) {
        this.funType = funType;
    }
}